/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/select-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["selectTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mfaSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mfaConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mfaVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mfa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mfaDisable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMemberships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPortalHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConsorcios"];
        put?: never;
        post: operations["createConsorcio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        get: operations["getConsorcio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateConsorcio"];
        trace?: never;
    };
    "/consorcios/{id}/unidades": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        get: operations["listUnidades"];
        put?: never;
        post: operations["createUnidad"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{id}/unidades/import-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createImportJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import-jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImportJobId"];
            };
            cookie?: never;
        };
        get: operations["getImportJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/import-jobs/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImportJobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmImportJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{id}/liquidaciones": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        get: operations["listLiquidaciones"];
        put?: never;
        post: operations["createLiquidacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{consorcioId}/liquidaciones/{liquidacionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                liquidacionId: components["parameters"]["LiquidacionId"];
            };
            cookie?: never;
        };
        get: operations["getLiquidacion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateLiquidacion"];
        trace?: never;
    };
    "/consorcios/{consorcioId}/liquidaciones/{liquidacionId}/calcular": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                liquidacionId: components["parameters"]["LiquidacionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["calcularLiquidacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{consorcioId}/liquidaciones/{liquidacionId}/confirmar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                liquidacionId: components["parameters"]["LiquidacionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmarLiquidacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{consorcioId}/liquidaciones/{liquidacionId}/publicar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                liquidacionId: components["parameters"]["LiquidacionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publicarLiquidacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{consorcioId}/liquidaciones/{liquidacionId}/anular": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                liquidacionId: components["parameters"]["LiquidacionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["anularLiquidacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{id}/gastos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        get: operations["listGastos"];
        put?: never;
        post: operations["createGasto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{id}/conceptos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        get: operations["listConceptos"];
        put?: never;
        post: operations["createConcepto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conceptos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConceptoId"];
            };
            cookie?: never;
        };
        get: operations["getConcepto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{consorcioId}/gastos/{gastoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                gastoId: components["parameters"]["GastoId"];
            };
            cookie?: never;
        };
        get: operations["getGasto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{id}/proveedores": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        get: operations["listProveedores"];
        put?: never;
        post: operations["createProveedor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unidades/{id}/cuenta-corriente": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UnidadId"];
            };
            cookie?: never;
        };
        get: operations["getCuentaCorriente"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{id}/cobranzas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        get: operations["listCobranzas"];
        put?: never;
        post: operations["createCobranza"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{id}/cobranzas/mercado-pago": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createMercadoPagoCobranza"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{id}/morosidad": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        get: operations["getMorosidad"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cobranzas/{id}/acreditar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CobranzaId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acreditarCobranza"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cobranzas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CobranzaId"];
            };
            cookie?: never;
        };
        get: operations["getCobranza"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cobranzas/{id}/recibo.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CobranzaId"];
            };
            cookie?: never;
        };
        get: operations["getCobranzaRecibo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{id}/unidades/{unidadId}/cuenta-corriente": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
                id: components["parameters"]["UnidadId"];
            };
            cookie?: never;
        };
        get: operations["getCuentaCorriente"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cobranzas/{id}/asignaciones": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CobranzaId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ajustarAsignaciones"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cobranzas/{id}/revertir": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CobranzaId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revertirCobranza"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{id}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["DocumentoId"];
            };
            cookie?: never;
        };
        get: operations["getDocumentDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/document-upload-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createDocumentUploadIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{id}/comunicados": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        get: operations["listComunicados"];
        put?: never;
        post: operations["createComunicado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comunicados/{id}/publicar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ComunicadoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publicarComunicado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consorcios/{id}/reclamos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        get: operations["listReclamos"];
        put?: never;
        post: operations["createReclamo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reclamos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReclamoId"];
            };
            cookie?: never;
        };
        get: operations["getReclamo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reclamos/{id}/mensajes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReclamoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addReclamoMensaje"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reclamos/{id}/transiciones": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReclamoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transicionReclamo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Money: {
            /**
             * Format: int64
             * @description Importe en centavos (nunca float).
             */
            amount_cents: number;
            /** @default ARS */
            currency: string;
        };
        ErrorField: {
            field: string;
            code: string;
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            code: string;
            detail: string;
            instance: string;
            /** Format: uuid */
            request_id: string;
            errors?: components["schemas"]["ErrorField"][];
        };
        Page: {
            data: unknown[];
            meta: {
                /** Format: uuid */
                request_id: string;
                page?: number;
                per_page?: number;
                total?: number;
            };
        };
        Cursor: {
            data: unknown[];
            meta: {
                /** Format: uuid */
                request_id: string;
                next_cursor: string | null;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            status: string;
            mfa_enabled?: boolean;
        };
        Membership: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            tenant_name: string;
            tenant_status?: string;
            roles: string[];
            scopes?: string[];
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            memberships: components["schemas"]["Membership"][];
        };
        PortalConsorcioSummary: {
            /** Format: uuid */
            id: string;
            nombre: string;
            estado: string;
            /** Format: int64 */
            saldo_vencido_cents: number;
            /** Format: int64 */
            cargos_vencidos: number;
            vencido_desde: string;
        };
        PortalReceiptSummary: {
            /** Format: uuid */
            consorcio_id: string;
            consorcio_nombre: string;
            /** Format: uuid */
            cobranza_id: string;
            fecha: string;
            /** Format: int64 */
            importe_cents: number;
            estado: string;
            /** Format: int64 */
            saldo_a_favor_cents: number;
            /** @description RFC3339 timestamp. */
            created_at: string;
        };
        PortalComunicadoSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            consorcio_id: string;
            consorcio_nombre: string;
            titulo: string;
            estado: string;
            /** @description RFC3339 timestamp. */
            publicado_at: string;
        };
        PortalReclamoSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            consorcio_id: string;
            /** Format: uuid */
            unidad_id: string;
            categoria: string;
            estado: string;
            texto: string;
            /** @description RFC3339 timestamp. */
            created_at: string;
        };
        PortalHome: {
            consorcios: components["schemas"]["PortalConsorcioSummary"][];
            recibos_recientes: components["schemas"]["PortalReceiptSummary"][];
            comunicados_recientes: components["schemas"]["PortalComunicadoSummary"][];
            reclamos_recientes: components["schemas"]["PortalReclamoSummary"][];
            /** Format: int64 */
            total_saldo_vencido_cents: number;
        };
        MfaSetup: {
            /** @description Secret TOTP */
            secret: string;
            /** @description URL otpauth:// para escanear con el autenticador */
            otpauth_url: string;
        };
        MfaRequiredResponse: {
            /** @enum {boolean} */
            mfa_required: true;
            /** @description Token de un solo propósito para /auth/mfa/verify, expira en minutos. */
            mfa_token: string;
        };
        Me: {
            user: components["schemas"]["User"];
            membership: components["schemas"]["Membership"];
            permissions: string[];
        };
        Consorcio: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            nombre: string;
            cuit?: string | null;
            domicilio?: string | null;
            tipo?: string;
            estado: string;
            /** Format: date-time */
            created_at?: string;
        };
        ConsorcioInput: {
            nombre: string;
            cuit?: string | null;
            domicilio?: string | null;
            /** @enum {string} */
            tipo?: "edificio" | "barrio" | "complejo" | "otros";
        };
        Unidad: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            consorcio_id: string;
            codigo: string;
            tipo: string;
            superficie?: number | null;
            /** @description NUMERIC(12,8), >= 0 */
            coeficiente: string;
            estado: string;
            /** @description Vínculos vigentes de la UF. */
            personas?: components["schemas"]["PersonaVinculo"][];
        };
        UnidadInput: {
            codigo: string;
            /** @enum {string} */
            tipo: "departamento" | "cochera" | "local" | "unidad_edificio" | "otros";
            superficie?: number | null;
            coeficiente?: string;
            /** @description Personas a vincular (crear o reusar por documento) al crear la UF. */
            personas?: components["schemas"]["PersonaVinculoInput"][];
        };
        Persona: {
            /** Format: uuid */
            id: string;
            nombre: string;
            documento?: string | null;
            email?: string | null;
            telefono?: string | null;
        };
        PersonaVinculo: {
            persona: components["schemas"]["Persona"];
            /** @enum {string} */
            vinculo: "propietario" | "inquilino" | "apoderado";
            porcentaje?: string | null;
            /** Format: date */
            valid_from?: string;
        };
        PersonaVinculoInput: {
            persona: {
                nombre: string;
                documento?: string | null;
                /** Format: email */
                email?: string | null;
                telefono?: string | null;
            };
            /** @enum {string} */
            vinculo: "propietario" | "inquilino" | "apoderado";
            porcentaje?: string | null;
            /** Format: date */
            valid_from?: string | null;
        };
        ImportJob: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            estado: "validando" | "listo" | "confirmando" | "procesado" | "fallido";
            total_filas?: number;
            creados?: number;
            actualizados?: number;
            rechazados?: number;
            errores?: components["schemas"]["ImportError"][];
            archivo_errores_url?: string | null;
        };
        ImportError: {
            fila: number;
            campos: {
                campo: string;
                error: string;
            }[];
        };
        Liquidacion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            consorcio_id: string;
            /** @description YYYYMM */
            periodo: string;
            /** Format: date */
            vencimiento_1: string;
            /** Format: date */
            vencimiento_2?: string | null;
            /** @enum {string} */
            estado: "borrador" | "calculada" | "confirmada" | "publicada" | "cerrada" | "anulada";
            version: number;
            /** Format: int64 */
            total_gastos_cents: number;
            /** Format: int64 */
            total_distribuido_cents: number;
            unidades_alcanzadas: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        LiquidacionInput: {
            periodo: string;
            /** Format: date */
            vencimiento_1: string;
            /** Format: date */
            vencimiento_2?: string | null;
        };
        LiquidacionGasto: {
            /** Format: uuid */
            liquidacion_id: string;
            /** Format: uuid */
            gasto_id: string;
            /** Format: uuid */
            concepto_id: string;
            /** Format: int64 */
            importe_cents: number;
        };
        LiquidacionItem: {
            /** Format: uuid */
            liquidacion_id: string;
            /** Format: uuid */
            concepto_id: string;
            regla_aplicada: string;
            /** Format: int64 */
            importe_cents: number;
        };
        LiquidacionUnidad: {
            /** Format: uuid */
            liquidacion_id: string;
            /** Format: uuid */
            unidad_id: string;
            codigo: string;
            coeficiente: number;
            /** Format: int64 */
            total_cents: number;
        };
        Gasto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            consorcio_id: string;
            /** Format: uuid */
            concepto_id: string;
            concepto_nombre?: string;
            /** Format: uuid */
            proveedor_id?: string | null;
            comprobante?: string | null;
            /** Format: int64 */
            importe_cents: number;
            /** Format: date */
            fecha: string;
            estado: string;
            /** Format: uuid */
            documento_id?: string | null;
        };
        Concepto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            consorcio_id?: string | null;
            nombre: string;
            categoria: string;
            /** @description regla de distribución: coeficiente */
            regla: string;
            /** Format: date-time */
            created_at?: string;
        };
        ConceptoInput: {
            nombre: string;
            /** @enum {string} */
            categoria: "administracion" | "servicios" | "mantenimiento" | "fondos" | "otros";
        };
        Proveedor: {
            /** Format: uuid */
            id: string;
            cuit: string;
            razon_social: string;
            contacto_nombre?: string | null;
            /** Format: email */
            contacto_email?: string | null;
            estado: string;
        };
        Cobranza: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            unidad_id: string;
            /** Format: date */
            fecha: string;
            canal?: string;
            importe: components["schemas"]["Money"];
            referencia?: string | null;
            /** @enum {string} */
            estado: "pendiente_revision" | "acreditado" | "rechazado" | "revertido";
            /** Format: int64 */
            saldo_a_favor_cents?: number;
        };
        MercadoPagoCobranza: {
            cobranza: components["schemas"]["Cobranza"];
            /** Format: uri */
            checkout_url: string;
            /** @enum {string} */
            provider: "mercadopago" | "mock";
            preference_id: string;
        };
        Reclamo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            unidad_id: string;
            categoria: string;
            /** @enum {string} */
            estado: "abierto" | "en_progreso" | "resuelto" | "cerrado";
            /** Format: uuid */
            responsable_id?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        ReclamoMensaje: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            reclamo_id: string;
            texto: string;
            /** Format: uuid */
            adjunto_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ReclamoTransicion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            reclamo_id: string;
            accion: string;
            motivo?: string | null;
            /** Format: uuid */
            responsable_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ReclamoDetalle: {
            reclamo: components["schemas"]["Reclamo"];
            mensajes: components["schemas"]["ReclamoMensaje"][];
            transiciones: components["schemas"]["ReclamoTransicion"][];
        };
        Comunicado: {
            /** Format: uuid */
            id: string;
            titulo: string;
            /** @enum {string} */
            estado: "borrador" | "publicado";
            destinatarios?: number;
        };
        DocumentDownload: {
            /** Format: uri */
            url: string;
            /** Format: date-time */
            expires_at: string;
        };
    };
    responses: {
        /** @description Error RFC 9457. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description ID idempotente de trazabilidad (se devuelve en respuesta). */
        RequestId: string;
        /** @description Obligatorio en confirmar, publicar, cobranzas, asignaciones y webhooks. */
        IdempotencyKey: string;
        IfMatch: string;
        ConsorcioId: string;
        UnidadId: string;
        ImportJobId: string;
        LiquidacionId: string;
        CobranzaId: string;
        DocumentoId: string;
        ComunicadoId: string;
        ReclamoId: string;
        ConceptoId: string;
        ConsorcioIdWide: string;
        GastoId: string;
    };
    requestBodies: never;
    headers: {
        RequestIdOut: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado del API (liveness). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Devuelve membresías (o mfa_required si el usuario tiene MFA); si hay más de una, el cliente llama a select-tenant. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"] | components["schemas"]["MfaRequiredResponse"];
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    selectTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    membership_id: string;
                };
            };
        };
        responses: {
            /** @description Emite access token contextual a la membresía elegida. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rota refresh y emite nuevo access token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoca refresh y sesión. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mfaSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Genera un secret TOTP y devuelve la URL otpauth para el QR. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaSetup"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    mfaConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Código TOTP de 6 dígitos */
                    code: string;
                };
            };
        };
        responses: {
            /** @description MFA habilitado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    mfaVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Token de un solo propósito emitido por /auth/login */
                    mfa_token: string;
                    /** @description Código TOTP de 6 dígitos */
                    code: string;
                };
            };
        };
        responses: {
            /** @description Segundo factor válido; emite refresh + access. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    mfaDisable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MFA deshabilitado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuario + membresía activa + permisos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listMemberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"][];
                };
            };
        };
    };
    getPortalHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumen del portal del tenant activo. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestIdOut"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PortalHome"];
                        meta: {
                            /** Format: uuid */
                            request_id: string;
                        };
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listConsorcios: {
        parameters: {
            query?: {
                q?: string;
                estado?: string;
            };
            header?: {
                /** @description ID idempotente de trazabilidad (se devuelve en respuesta). */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de consorcios del tenant activo. */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestIdOut"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    createConsorcio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsorcioInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consorcio"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    getConsorcio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consorcio"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateConsorcio: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConsorcioInput"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consorcio"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    listUnidades: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    createUnidad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UnidadInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unidad"];
                };
            };
            /** @description Código duplicado en el consorcio. */
            409: components["responses"]["Problem"];
        };
    };
    createImportJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    archivo: string;
                    /** @enum {string} */
                    modo: "crear" | "actualizar" | "crear_y_actualizar";
                };
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJob"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getImportJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ImportJobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJob"];
                };
            };
        };
    };
    confirmImportJob: {
        parameters: {
            query?: never;
            header?: {
                /** @description Obligatorio en confirmar, publicar, cobranzas, asignaciones y webhooks. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["ImportJobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJob"];
                };
            };
        };
    };
    listLiquidaciones: {
        parameters: {
            query?: {
                periodo?: string;
                estado?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    createLiquidacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LiquidacionInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liquidacion"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    getLiquidacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                liquidacionId: components["parameters"]["LiquidacionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liquidacion"];
                };
            };
        };
    };
    updateLiquidacion: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                liquidacionId: components["parameters"]["LiquidacionId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: date */
                    vencimiento_1?: string;
                    /** Format: date */
                    vencimiento_2?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liquidacion"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    calcularLiquidacion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Obligatorio en confirmar, publicar, cobranzas, asignaciones y webhooks. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                liquidacionId: components["parameters"]["LiquidacionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liquidacion"];
                };
            };
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    confirmarLiquidacion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Obligatorio en confirmar, publicar, cobranzas, asignaciones y webhooks. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                liquidacionId: components["parameters"]["LiquidacionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Congela snapshot y genera cargos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liquidacion"];
                };
            };
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
        };
    };
    publicarLiquidacion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Obligatorio en confirmar, publicar, cobranzas, asignaciones y webhooks. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                liquidacionId: components["parameters"]["LiquidacionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liquidacion"];
                };
            };
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
        };
    };
    anularLiquidacion: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                liquidacionId: components["parameters"]["LiquidacionId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    motivo?: string;
                };
            };
        };
        responses: {
            /** @description Asientos compensatorios generados; nada se borra. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liquidacion"];
                };
            };
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
        };
    };
    listGastos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    createGasto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    concepto_id: string;
                    /** Format: uuid */
                    proveedor_id?: string | null;
                    comprobante?: string | null;
                    /** Format: int64 */
                    importe_cents: number;
                    /** Format: date */
                    fecha: string;
                    /** Format: uuid */
                    documento_id?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gasto"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    listConceptos: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    createConcepto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConceptoInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Concepto"];
                };
            };
        };
    };
    getConcepto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConceptoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Concepto"];
                };
            };
        };
    };
    getGasto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consorcioId: components["parameters"]["ConsorcioIdWide"];
                gastoId: components["parameters"]["GastoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gasto"];
                };
            };
        };
    };
    listProveedores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    createProveedor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    cuit: string;
                    razon_social: string;
                    contacto_nombre?: string | null;
                    /** Format: email */
                    contacto_email?: string | null;
                    contacto_telefono?: string | null;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proveedor"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    getCuentaCorriente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UnidadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Movimientos y saldo reconstruido de la UF. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: int64 */
                        saldo_cents?: number;
                        /** Format: int64 */
                        saldo_a_favor_cents?: number;
                        movimientos?: components["schemas"]["Cursor"];
                    };
                };
            };
        };
    };
    listCobranzas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    createCobranza: {
        parameters: {
            query?: never;
            header?: {
                /** @description Obligatorio en confirmar, publicar, cobranzas, asignaciones y webhooks. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    unidad_id: string;
                    /** Format: date */
                    fecha: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cobranza"];
                };
            };
            /** @description Referencia duplicada; requiere resolución. */
            409: components["responses"]["Problem"];
        };
    };
    createMercadoPagoCobranza: {
        parameters: {
            query?: never;
            header?: {
                /** @description Obligatorio en confirmar, publicar, cobranzas, asignaciones y webhooks. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    unidad_id: string;
                    /** Format: date */
                    fecha: string;
                    importe: components["schemas"]["Money"];
                    referencia?: string | null;
                };
            };
        };
        responses: {
            /** @description Cobranza creada con enlace de checkout de Mercado Pago. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MercadoPagoCobranza"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    getMorosidad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumen de deuda vencida por UF. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** Format: uuid */
                            unidad_id?: string;
                            unidad_codigo?: string;
                            /** Format: int64 */
                            saldo_vencido_cents?: number;
                            /** Format: int64 */
                            cantidad_cargos?: number;
                            /** Format: date */
                            vencido_desde?: string;
                        }[];
                        meta?: {
                            /** Format: uuid */
                            request_id?: string;
                            /** Format: int64 */
                            total_saldo_cents?: number;
                            /** Format: int64 */
                            total_cargos_vencidos?: number;
                        };
                    };
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    acreditarCobranza: {
        parameters: {
            query?: never;
            header?: {
                /** @description Obligatorio en confirmar, publicar, cobranzas, asignaciones y webhooks. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["CobranzaId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Opcional; si se omite, el backend propone FIFO. */
                    asignaciones?: {
                        /** Format: uuid */
                        charge_id: string;
                        /** Format: int64 */
                        amount_cents: number;
                    }[];
                };
            };
        };
        responses: {
            /** @description Pago acreditado con asignaciones y saldo resultante. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        cobranza?: components["schemas"]["Cobranza"];
                        asignaciones?: {
                            /** Format: uuid */
                            charge_id?: string;
                            /** Format: int64 */
                            amount_cents?: number;
                        }[];
                        /** Format: int64 */
                        saldo_a_favor_cents?: number;
                    };
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    getCobranza: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CobranzaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cobranza con detalle de asignaciones y saldo a favor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        cobranza?: components["schemas"]["Cobranza"];
                        asignaciones?: {
                            /** Format: uuid */
                            charge_id?: string;
                            /** Format: int64 */
                            amount_cents?: number;
                        }[];
                        /** Format: int64 */
                        saldo_a_favor_cents?: number;
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getCobranzaRecibo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CobranzaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF descargable del recibo de la cobranza. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getCuentaCorriente: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UnidadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Libro de movimientos de una UF. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            unidad_id?: string;
                            tipo?: string;
                            /** Format: date */
                            fecha_efectiva?: string;
                            /** Format: int64 */
                            debit_cents?: number;
                            /** Format: int64 */
                            credit_cents?: number;
                            currency?: string;
                            referencia?: string | null;
                        }[];
                        meta?: {
                            /** Format: uuid */
                            request_id?: string;
                            /** Format: int64 */
                            saldo_cents?: number;
                        };
                    };
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    ajustarAsignaciones: {
        parameters: {
            query?: never;
            header?: {
                /** @description Obligatorio en confirmar, publicar, cobranzas, asignaciones y webhooks. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["CobranzaId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    asignaciones: {
                        /** Format: uuid */
                        charge_id: string;
                        /** Format: int64 */
                        amount_cents: number;
                    }[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        cobranza?: components["schemas"]["Cobranza"];
                        asignaciones?: {
                            /** Format: uuid */
                            charge_id?: string;
                            /** Format: int64 */
                            amount_cents?: number;
                        }[];
                        /** Format: int64 */
                        saldo_a_favor_cents?: number;
                    };
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    revertirCobranza: {
        parameters: {
            query?: never;
            header?: {
                /** @description Obligatorio en confirmar, publicar, cobranzas, asignaciones y webhooks. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["CobranzaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cobranza revertida con asignaciones restauradas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        cobranza?: components["schemas"]["Cobranza"];
                        asignaciones?: {
                            /** Format: uuid */
                            charge_id?: string;
                            /** Format: int64 */
                            amount_cents?: number;
                        }[];
                        /** Format: int64 */
                        saldo_a_favor_cents?: number;
                    };
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    getDocumentDownloadUrl: {
        parameters: {
            query?: never;
            header?: {
                /** @description ID idempotente de trazabilidad (se devuelve en respuesta). */
                "X-Request-ID"?: components["parameters"]["RequestId"];
            };
            path: {
                id: components["parameters"]["DocumentoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description URL firmada breve, emitida solo tras autorizar el recurso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDownload"];
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    createDocumentUploadIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    tipo: string;
                    nombre: string;
                    /** Format: int64 */
                    size_bytes: number;
                    sha256: string;
                    owner_type?: string;
                    /** Format: uuid */
                    owner_id?: string;
                };
            };
        };
        responses: {
            /** @description Intento con URL firmada de subida y documento_id. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        documento_id?: string;
                        /** Format: uri */
                        upload_url?: string;
                    };
                };
            };
            413: components["responses"]["Problem"];
        };
    };
    listComunicados: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    createComunicado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    titulo: string;
                    cuerpo: string;
                    /** @enum {string} */
                    destinatarios?: "todos" | "unidades";
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comunicado"];
                };
            };
        };
    };
    publicarComunicado: {
        parameters: {
            query?: never;
            header?: {
                /** @description Obligatorio en confirmar, publicar, cobranzas, asignaciones y webhooks. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["ComunicadoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Envíos encolados en el worker. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comunicado"];
                };
            };
        };
    };
    listReclamos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    createReclamo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ConsorcioId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    unidad_id: string;
                    categoria: string;
                    texto: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reclamo"];
                };
            };
            403: components["responses"]["Problem"];
        };
    };
    getReclamo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReclamoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReclamoDetalle"];
                };
            };
        };
    };
    addReclamoMensaje: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReclamoId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    texto: string;
                    /** Format: uuid */
                    adjunto_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Mensaje agregado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    transicionReclamo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReclamoId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    accion: "asignar" | "en_progreso" | "resolver" | "cerrar" | "reabrir";
                    motivo: string | null;
                    /** Format: uuid */
                    responsable_id?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reclamo"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                cursor?: string;
                accion?: string;
                recurso_type?: string;
                desde?: string;
                hasta?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auditoría append-only paginada por cursor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cursor"];
                };
            };
        };
    };
}
